export const FILES_CONSTANTS = {
  CONTROLLER: {
    TAG: 'Files',
    PATH: 'files',
  },
  UPLOAD: {
    MAX_FILE_SIZE: 10 * 1024 * 1024,
    MAX_FILES_COUNT: 5,
    DIRECTORY: 'uploads',
    FIELD_NAME_SINGLE: 'file',
    FIELD_NAME_MULTIPLE: 'files',
    ALLOWED_MIMES: [
      'image/jpeg',
      'image/jpg',
      'image/png',
      'image/gif',
      'image/webp',
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ],
  },
  ROUTES: {
    UPLOAD: 'upload',
    UPLOAD_MULTIPLE: 'upload-multiple',
    STATS: 'stats',
    DOWNLOAD: ':id/download',
    CLEANUP: 'cleanup',
  },
  QUERY_PARAMS: {
    PAGE: 'page',
    LIMIT: 'limit',
    ID: 'id',
  },
  HTTP_HEADERS: {
    CONTENT_TYPE: 'Content-Type',
    CONTENT_DISPOSITION: 'Content-Disposition',
    CONTENT_LENGTH: 'Content-Length',
    DEFAULT_CONTENT_TYPE: 'application/octet-stream',
  },
  API: {
    CONSUMES_MULTIPART: 'multipart/form-data',
    UPLOAD_SUMMARY: 'Загрузка одного файла',
    UPLOAD_MULTIPLE_SUMMARY: 'Загрузка нескольких файлов',
    GET_FILES_SUMMARY: 'Получить список файлов пользователя',
    GET_STATS_SUMMARY: 'Получить статистику файлов пользователя',
    GET_FILE_INFO_SUMMARY: 'Получить информацию о файле',
    DOWNLOAD_FILE_SUMMARY: 'Скачать файл',
    DELETE_FILE_SUMMARY: 'Удалить файл',
    CLEANUP_SUMMARY: 'Очистка осиротевших файлов (только для разработки)',
    DOWNLOAD_DESCRIPTION: 'Файл для скачивания',
  },
  ENTITY: {
    TABLE_NAME: 'files',
    DESCRIPTIONS: {
      ID: 'ID файла',
      ORIGINAL_NAME: 'Оригинальное имя файла',
      FILENAME: 'Имя файла на сервере',
      PATH: 'Путь к файлу',
      MIMETYPE: 'MIME тип файла',
      SIZE: 'Размер файла в байтах',
      USER_ID: 'ID пользователя-владельца',
      CREATED_AT: 'Дата создания',
      UPDATED_AT: 'Дата обновления',
    },
  },
  DATABASE: {
    ORDER_BY: 'createdAt',
    ORDER_DIRECTION: 'DESC',
    ATTRIBUTES: {
      FILENAME: 'filename',
      MIMETYPE: 'mimetype',
      SIZE: 'size',
    },
  },
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 10,
  },
  SIZE: {
    BYTES_IN_MB: 1024 * 1024,
  },
  PARSING: {
    DECIMAL_RADIX: 10,
  },
  MESSAGES: {
    FILE_UPLOADED: 'Файл успешно загружен',
    FILES_UPLOADED: 'Загружено файлов',
    FILE_NOT_PROVIDED: 'Файл не предоставлен',
    FILES_NOT_PROVIDED: 'Файлы не предоставлены',
    FILE_NOT_FOUND: 'Файл не найден',
    FILE_NOT_FOUND_ON_DISK: 'Файл не найден на диске',
    FILE_DELETED: 'Файл успешно удален',
    FILES_LIST: 'Список файлов пользователя',
    FILE_INFO: 'Информация о файле',
    FILE_STATS: 'Статистика файлов',
    CLEANUP_COMPLETED: 'Очистка завершена',
    CLEANUP_ERROR: 'Ошибка при очистке файлов',
    UNSUPPORTED_FILE_TYPE: 'Неподдерживаемый тип файла',
    ALLOWED_TYPES: 'Разрешены',
    SAVE_ERROR: 'Ошибка при сохранении файла',
    DELETE_ERROR: 'Ошибка при удалении файла',
    UNKNOWN_TYPE: 'unknown',
    OR: 'или',
    LIMIT_EXCEEDED: 'превышен лимит',
  },
};