export const AUTH_CONSTANTS = {
  JWT: {
    ACCESS_TOKEN_EXPIRES_IN: 15 * 60,
    REFRESH_TOKEN_EXPIRES_DAYS: 7,
    ACCESS_SECRET_ENV: 'JWT_ACCESS_SECRET',
    REFRESH_SECRET_ENV: 'JWT_REFRESH_SECRET',
    ACCESS_EXPIRES_IN_ENV: 'JWT_ACCESS_EXPIRES_IN',
    REFRESH_EXPIRES_IN_ENV: 'JWT_REFRESH_EXPIRES_IN',
    DEFAULT_EXPIRES_IN: '15m',
    DEFAULT_REFRESH_EXPIRES_IN: '7d',
    DEFAULT_STRATEGY: 'jwt',
  },
  BCRYPT: {
    SALT_ROUNDS: 12,
  },
  VALIDATION: {
    PASSWORD_MIN_LENGTH: 6,
    PASSWORD_MAX_LENGTH: 50,
    NAME_MAX_LENGTH: 50,
  },
  SWAGGER: {
    REGISTER_SUMMARY: 'Регистрация нового пользователя',
    LOGIN_SUMMARY: 'Вход в систему',
    REFRESH_SUMMARY: 'Обновление токенов',
    PROFILE_SUMMARY: 'Получение профиля текущего пользователя',
    LOGOUT_SUMMARY: 'Выход из системы',
  },
  DTO: {
    EMAIL_DESCRIPTION: 'Email пользователя',
    EMAIL_EXAMPLE: 'user@example.com',
    PASSWORD_DESCRIPTION: 'Пароль пользователя',
    PASSWORD_EXAMPLE: 'password123',
    FIRST_NAME_DESCRIPTION: 'Имя пользователя',
    FIRST_NAME_EXAMPLE: 'Иван',
    LAST_NAME_DESCRIPTION: 'Фамилия пользователя',
    LAST_NAME_EXAMPLE: 'Иванов',
    REFRESH_TOKEN_PARAM: 'refreshToken',
  },
  MESSAGES: {
    USER_ALREADY_EXISTS: 'Пользователь с таким email уже существует',
    REGISTER_SUCCESS: 'Пользователь успешно зарегистрирован',
    LOGIN_SUCCESS: 'Успешная авторизация',
    INVALID_CREDENTIALS: 'Неверные учетные данные',
    USER_NOT_FOUND: 'Пользователь не найден',
    INVALID_TOKEN: 'Недействительный токен',
    INVALID_REFRESH_TOKEN: 'Недействительный refresh token',
    TOKENS_REFRESHED: 'Токены успешно обновлены',
    LOGOUT_SUCCESS: 'Успешный выход из системы',
    PROFILE_DATA: 'Профиль пользователя',
    INVALID_EMAIL: 'Некорректный email адрес',
    PASSWORD_STRING: 'Пароль должен быть строкой',
    PASSWORD_NOT_EMPTY: 'Пароль не может быть пустым',
    PASSWORD_MIN_LENGTH: 'Пароль должен содержать минимум 6 символов',
    PASSWORD_MAX_LENGTH: 'Пароль не должен превышать 50 символов',
    NAME_STRING: 'Имя должно быть строкой',
    NAME_MAX_LENGTH: 'Имя не должно превышать 50 символов',
    LAST_NAME_STRING: 'Фамилия должна быть строкой',
    LAST_NAME_MAX_LENGTH: 'Фамилия не должна превышать 50 символов',
  },
  ERRORS: {
    INTERNAL_ERROR: 'Внутренняя ошибка сервера',
    TOKEN_EXPIRED: 'Токен истек',
    TOKEN_INVALID: 'Недействительный токен',
  },
};