export const WEBSOCKET_CONSTANTS = {
  EVENTS: {
    CONNECTION: 'connection',
    DISCONNECT: 'disconnect',
    AUTHENTICATE: 'authenticate',
    JOIN_ROOM: 'join_room',
    LEAVE_ROOM: 'leave_room',
    SEND_MESSAGE: 'send_message',
    AUTHENTICATED: 'authenticated',
    AUTHENTICATION_ERROR: 'authentication_error',
    USER_ONLINE: 'user_online',
    USER_OFFLINE: 'user_offline',
    NEW_MESSAGE: 'new_message',
    FILE_UPLOADED: 'file_uploaded',
    USER_UPDATED: 'user_updated',
    JOINED_ROOM: 'joined_room',
    LEFT_ROOM: 'left_room',
    NOTIFICATION: 'notification',
    BROADCAST_NOTIFICATION: 'broadcast_notification',
    USER_PREFIX: 'user_',
    ERROR: 'error',
  },
  MESSAGES: {
    GATEWAY_INITIALIZED: 'WebSocket Gateway инициализирован',
    CLIENT_CONNECTED: 'Клиент подключился',
    CLIENT_DISCONNECTED: 'Клиент отключился',
    USER_CONNECTED: 'Пользователь подключен',
    USER_DISCONNECTED: 'Пользователь отключен',
    USER_AUTHENTICATED: 'Пользователь аутентифицирован',
    USER_AUTHENTICATED_VIA_MESSAGE: 'Пользователь аутентифицирован через сообщение',
    USER_JOINED_ROOM: 'Пользователь присоединился к комнате',
    USER_LEFT_ROOM: 'Пользователь покинул комнату',
    AUTHENTICATION_SUCCESS: 'Аутентификация успешна',
    AUTHENTICATION_FAILED: 'Ошибка аутентификации',
    AUTH_ERROR: 'Ошибка аутентификации',
    JOINED_ROOM: 'Присоединился к комнате',
    LEFT_ROOM: 'Покинул комнату',
    MESSAGE_SENT: 'Сообщение отправлено',
    INVALID_TOKEN: 'Недействительный токен',
    ROOM_REQUIRED: 'Название комнаты обязательно',
    MESSAGE_REQUIRED: 'Сообщение обязательно',
  },
  AUTH: {
    BEARER_PREFIX: 'Bearer ',
    BEARER_PREFIX_LENGTH: 7,
    TOKEN_NOT_PROVIDED: 'Токен не предоставлен',
    JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  },
  ERRORS: {
    AUTHENTICATION_ERROR: 'Ошибка аутентификации',
    TOKEN_MISSING: 'Токен отсутствует',
    TOKEN_INVALID: 'Недействительный токен',
    USER_NOT_FOUND: 'Пользователь не найден',
    ROOM_ERROR: 'Ошибка при работе с комнатой',
    MESSAGE_ERROR: 'Ошибка при отправке сообщения',
  },
};